install:
  # - xelatex ARIES
  # - xelatex write-behind-logging
  # - xelatex lsm-tree
  # - xelatex bigtable
  # - xelatex eliminate-unscalable-communication
  # - xelatex f1
  # - xelatex dremel
  # - xelatex heron
  # - xelatex data-ingestion-connected-world
  # - xelatex concurrency_control_performance_modeling
  - xelatex cryptdb
scripts:
  clean:
    - sh -c "rm -f *.log *.aux *.out"
