install:
  # - xelatex ARIES
  # - xelatex write-behind-logging
  # - xelatex lsm-tree
  # - xelatex bigtable
  - xelatex eliminate-unscalable-communication
scripts:
  clean:
    - sh -c "rm -f *.log *.aux *.out"
